### ISSUE TITLE
This is not a method of this class. It should be placed in the `./utils`

### ISSUE THREAD

**Issue by DScheglov** [Cath-kb/js-school#5]
https://github.com/Cath-kb/js-school/blob/b5db56fa85acfc34fd4eb79d7ce745b9b9fc405e/lesson15/github-user-edit/src/components/User/Form.js#L19

**Comment by Cath-kb** [comment]
Thank you! Fixed https://github.com/Cath-kb/js-school/blob/master/lesson15/github-user-edit/src/utils/common.js#L1
